# Generated by Django 4.0.5 on 2022-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_type',
            field=models.PositiveBigIntegerField(choices=[(1, 'Free'), (2, 'silver'), (3, 'Gold'), (4, 'Premium')], default=1),
        ),
    ]
