# Generated by Django 4.0.5 on 2022-06-20 12:55

from audioop import reverse
from typing import Set
from django.db import migrations

from accounts.models import User

def change(apps, schema_editor ):
    user=apps.get_model("accounts","User")
    user.objects.filter(subs=True).update(sub_type=3) # Böyle Yaparsan n adet işlem kar ederiz
    # for veri in user.objects.all():
    #     if veri.subs:
    #         veri.sub_type=2
    #         veri.save()
            
        

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sub_type'),
    ]

    operations = [migrations.RunPython( change, reverse_code=migrations.RunPython.noop)]
