# Generated by Django 4.0.5 on 2022-06-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='oluşturma tarihi'),
        ),
        migrations.AddField(
            model_name='url',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='url_show',
            field=models.BooleanField(default=True),
        ),
    ]
