# Generated by Django 4.0.5 on 2022-06-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_url_author_url_created_date_url_deleted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
