# Generated by Django 4.0.5 on 2022-06-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_url_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='subs',
            field=models.BooleanField(default=False),
        ),
    ]
